organization := "it.contactlab.hub"
name := "sdk-java"
description := "ContactHUB Java SDK"
autoScalaLibrary := false
scalaVersion := scalaV
libraryDependencies ++= testDependencies ++ dependencies
publishMavenStyle := true
crossPaths := false
publishTo := Some("buildo private maven" at "https://buildo-private-maven.appspot.com/")
credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")
javacOptions in doc ++= Seq("-sourcepath", "target/classes", "-subpackages", "it.contactlab")

enablePlugins(GitVersioning)

// Always run the "compile" task before the "doc" task, because some of the
// sources are autogenerated by Immutables at compile time.
doc in Compile := {
  (compile in Compile).value
  (doc in Compile).value
}

// Run checkstyle when compiling
// jcheckStyleConfig := "checkstyle-config.xml"
// compile in Compile := {
//   (jcheckStyle in Compile).value
//   (compile in Compile).value
// }

lazy val scalaV = "2.12.1"

lazy val testDependencies = Seq(
  "org.scalatest" %% "scalatest" % "3.0.0",
  "org.scala-lang" % "scala-library" % scalaV,
  "org.scala-lang.modules" % "scala-java8-compat_2.11" % "0.8.0-RC7",
  "org.scalacheck" %% "scalacheck" % "1.13.4"
).map(_ % "test")

lazy val dependencies = Seq(
  "org.immutables" % "value" % "2.3.7",
  "com.mashape.unirest" % "unirest-java" % "1.4.9",
  "com.google.code.gson" % "gson" % "2.7",
  "com.google.code.findbugs" % "jsr305" % "3.0.0"
)

lazy val root = project.in(file("."))

lazy val example = project.in(file("example")).dependsOn(root)
